---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
- Phuoc's note: "This is a line from RStudio Test Group"
"This is the line added by Jaren"
"This is the line added by Tyler" 
# Lab report #1

12.1:

12.2:

12.3:
-Jaren's note: uploaded the wrong link and had to restart the project.
12.4:

12.5:
Pushed multiple times without pulling which broke the file. I had to restart and remake my changes after deleting the files on my device.
12.6:


Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.
